# Generated by Django 3.2.6 on 2023-05-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_auto_20230502_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320, verbose_name='作者')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_name', models.CharField(max_length=320, verbose_name='出版社名称')),
                ('author', models.ManyToManyField(to='books.Author', verbose_name='作者id')),
            ],
            options={
                'db_table': 'press',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320, verbose_name='书名')),
                ('text', models.TextField(verbose_name='简介')),
                ('price', models.FloatField(verbose_name='价格')),
                ('date', models.DateField(verbose_name='时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.author', verbose_name='作者')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.press', verbose_name='出版社')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
