# Generated by Django 3.2.6 on 2023-05-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_books_press'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='文件名称')),
                ('wen', models.FileField(upload_to='wood/%Y%m%d', verbose_name='文件路径')),
            ],
        ),
    ]
