# Generated by Django 3.2.6 on 2023-05-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_files'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='files',
            table='files',
        ),
    ]
