# Generated by Django 3.2.6 on 2023-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('level', models.CharField(choices=[('1', '1级'), ('2', '2级'), ('3', '3级'), ('4', '4级')], max_length=12, verbose_name='靓号等级')),
                ('status', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'db_table': 'pretty',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门表', 'verbose_name_plural': '部门表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '员工表', 'verbose_name_plural': '员工表'},
        ),
    ]
