# Generated by Django 3.2.6 on 2023-05-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Four',
        ),
        migrations.DeleteModel(
            name='One',
        ),
        migrations.DeleteModel(
            name='Three',
        ),
        migrations.DeleteModel(
            name='Two',
        ),
    ]
