# Generated by Django 3.2.6 on 2023-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20230523_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='题目')),
                ('an', models.TextField(verbose_name='答案')),
            ],
            options={
                'db_table': 'four',
            },
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='题目')),
                ('A', models.CharField(max_length=256, verbose_name='选项A')),
                ('B', models.CharField(max_length=256, verbose_name='选项B')),
                ('C', models.CharField(max_length=256, verbose_name='选项C')),
                ('D', models.CharField(max_length=256, verbose_name='选项D')),
                ('an', models.CharField(max_length=500, verbose_name='答案')),
            ],
            options={
                'db_table': 'one',
            },
        ),
        migrations.CreateModel(
            name='Three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='题目')),
                ('an', models.CharField(max_length=600, verbose_name='答案')),
            ],
            options={
                'db_table': 'three',
            },
        ),
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='题目')),
                ('A', models.CharField(max_length=256, verbose_name='选项A')),
                ('B', models.CharField(max_length=256, verbose_name='选项B')),
                ('C', models.CharField(max_length=256, verbose_name='选项C')),
                ('D', models.CharField(max_length=256, verbose_name='选项D')),
                ('an', models.CharField(max_length=600, verbose_name='答案')),
            ],
            options={
                'db_table': 'two',
            },
        ),
    ]
